services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: visionpv_api
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
